In [17]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime
from sqlalchemy import text

In [18]:
url = "C:\\Users\\lucas\\Downloads\\acidentes2022\\acidentes2022.csv"

df = pd.read_csv(url, sep=';', encoding='latin1')

In [19]:
df.dtypes

id                         int64
pesid                      int64
data_inversa              object
dia_semana                object
horario                   object
uf                        object
br                         int64
km                        object
municipio                 object
causa_acidente            object
tipo_acidente             object
classificacao_acidente    object
fase_dia                  object
sentido_via               object
condicao_metereologica    object
tipo_pista                object
tracado_via               object
uso_solo                  object
id_veiculo                 int64
tipo_veiculo              object
marca                     object
ano_fabricacao_veiculo     int64
tipo_envolvido            object
estado_fisico             object
idade                      int64
sexo                      object
ilesos                     int64
feridos_leves              int64
feridos_graves             int64
mortos                     int64
latitude                  object
longitude                 object
regional                  object
delegacia                 object
uop                       object
dtype: object

In [20]:
df['data_inversa'] = pd.to_datetime(df['data_inversa'], format='%Y-%m-%d')

In [21]:
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,405151,910368,2022-01-01,sábado,01:35:00,PI,316,415,MARCOLANDIA,Ingestão de álcool pelo condutor,...,Masculino,1,0,0,0,"-7,43280012","-40,68261908",SPRF-PI,DEL04-PI,UOP03-DEL04-PI
1,405158,906468,2022-01-01,sábado,02:40:00,PR,116,33,CAMPINA GRANDE DO SUL,Ingestão de álcool pelo condutor,...,Feminino,0,0,0,1,"-25,114403","-48,8467554",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
2,405158,912108,2022-01-01,sábado,02:40:00,PR,116,33,CAMPINA GRANDE DO SUL,Ingestão de álcool pelo condutor,...,Masculino,0,1,0,0,"-25,114403","-48,8467554",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
3,405172,909365,2022-01-01,sábado,05:22:00,MS,163,393,NOVA ALVORADA DO SUL,Condutor deixou de manter distância do veículo...,...,Masculino,1,0,0,0,"-21,228445","-54,456296",SPRF-MS,DEL02-MS,UOP01-DEL02-MS
4,405203,906368,2022-01-01,sábado,07:00:00,RJ,101,457,ANGRA DOS REIS,Reação tardia ou ineficiente do condutor,...,Masculino,1,0,0,0,"-23,03149804","-44,17715297",SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170820,621057,1390206,2022-07-03,domingo,00:52:00,TO,153,137,ARAGUAINA,Velocidade Incompatível,...,Feminino,0,1,0,0,"-7,14630299","-48,20255603",NaN,NaN,NaN
170821,621057,1390207,2022-07-03,domingo,00:52:00,TO,153,137,ARAGUAINA,Velocidade Incompatível,...,Masculino,0,1,0,0,"-7,14630299","-48,20255603",NaN,NaN,NaN
170822,621057,1390219,2022-07-03,domingo,00:52:00,TO,153,137,ARAGUAINA,Velocidade Incompatível,...,Feminino,0,0,1,0,"-7,14630299","-48,20255603",NaN,NaN,NaN
170823,621057,1390208,2022-07-03,domingo,00:52:00,TO,153,137,ARAGUAINA,Velocidade Incompatível,...,Feminino,0,1,0,0,"-7,14630299","-48,20255603",NaN,NaN,NaN
170824,621057,1390228,2022-07-03,domingo,00:52:00,TO,153,137,ARAGUAINA,Velocidade Incompatível,...,Não Informado,0,0,0,0,"-7,14630299","-48,20255603",NaN,NaN,NaN

In [22]:
df['uso_solo'] = df['uso_solo'].str.strip().str.lower().map({
    'Sim' : True,
    'Não' : False,
    'nao' : False
})
df['uso_solo'] = df['uso_solo'].where(df['uso_solo'].notnull(), None)
df['uso_solo'] = df['uso_solo'].astype('bool')

In [23]:
df[['km']].dtypes

km    object
dtype: object

In [24]:
df['km'] = df['km'].str.replace('.', '', regex=False)
df['km'] = df['km'].str.replace(',', '.', regex=False)
df['km'] = df['km'].astype(float)

In [25]:
df['latitude'] = df['latitude'].str.replace(',', '.', regex=False)
df['longitude'] = df['longitude'].str.replace(',', '.', regex=False)
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

In [26]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip()

In [27]:
print(df.isnull().sum())

id                        0
pesid                     0
data_inversa              0
dia_semana                0
horario                   0
uf                        0
br                        0
km                        0
municipio                 0
causa_acidente            0
tipo_acidente             0
classificacao_acidente    0
fase_dia                  0
sentido_via               0
condicao_metereologica    0
tipo_pista                0
tracado_via               0
uso_solo                  0
id_veiculo                0
tipo_veiculo              0
marca                     0
ano_fabricacao_veiculo    0
tipo_envolvido            0
estado_fisico             0
idade                     0
sexo                      0
ilesos                    0
feridos_leves             0
feridos_graves            0
mortos                    0
latitude                  0
longitude                 0
regional                  0
delegacia                 0
uop                       0
dtype: int64

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
if df['id'].duplicated().any():
    print('ATENÇÃO: IDs duplicados encontrados!')
else:
    print('ATENÇÃO: IDs duplicados não encontrados!')

ATENÇÃO: IDs duplicados encontrados!

In [30]:
df_duplicados = df[df['id'].duplicated(keep=False)]

print(df_duplicados.sort_values('id'))

            id    pesid data_inversa dia_semana   horario  uf   br     km  \
37613   405147   911178   2022-01-01     sábado  00:10:00  CE  222    2.8
37612   405147   911179   2022-01-01     sábado  00:10:00  CE  222    2.8
37617   405149   913204   2022-01-01     sábado  01:30:00  PE  104   63.0
37616   405149   912788   2022-01-01     sábado  01:30:00  PE  104   63.0
37615   405149   912796   2022-01-01     sábado  01:30:00  PE  104   63.0
...        ...      ...          ...        ...       ...  ..  ...    ...
170810  621057  1390220   2022-07-03    domingo  00:52:00  TO  153  137.0
170815  621057  1390225   2022-07-03    domingo  00:52:00  TO  153  137.0
170814  621057  1390224   2022-07-03    domingo  00:52:00  TO  153  137.0
170812  621057  1390222   2022-07-03    domingo  00:52:00  TO  153  137.0
170823  621057  1390208   2022-07-03    domingo  00:52:00  TO  153  137.0

        municipio                                     causa_acidente  ...  \
37613   FORTALEZA                   Ingestão de álcool pelo condutor  ...
37612   FORTALEZA                   Ingestão de álcool pelo condutor  ...
37617     CARUARU  Condutor desrespeitou a iluminação vermelha do...  ...
37616     CARUARU  Condutor desrespeitou a iluminação vermelha do...  ...
37615     CARUARU  Condutor desrespeitou a iluminação vermelha do...  ...
...           ...                                                ...  ...
170810  ARAGUAINA                            Velocidade Incompatível  ...
170815  ARAGUAINA                            Velocidade Incompatível  ...
170814  ARAGUAINA                            Velocidade Incompatível  ...
170812  ARAGUAINA                            Velocidade Incompatível  ...
170823  ARAGUAINA                            Velocidade Incompatível  ...

                 sexo ilesos feridos_leves feridos_graves mortos  latitude  \
37613       Masculino      1             0              0      0 -3.739111
37612       Masculino      0             0              1      0 -3.739111
37617   Não Informado      0             0              0      0 -8.269800
37616       Masculino      1             0              0      0 -8.269800
37615        Feminino      0             1              0      0 -8.269800
...               ...    ...           ...            ...    ...       ...
170810       Feminino      1             0              0      0 -7.146303
170815      Masculino      0             1              0      0 -7.146303
170814      Masculino      0             1              0      0 -7.146303
170812       Feminino      1             0              0      0 -7.146303
170823       Feminino      0             1              0      0 -7.146303

        longitude  regional  delegacia             uop
37613  -38.586875   SPRF-CE   DEL01-CE  UOP01-DEL01-CE
37612  -38.586875   SPRF-CE   DEL01-CE  UOP01-DEL01-CE
37617  -35.980300   SPRF-PE   DEL02-PE  UOP01-DEL02-PE
37616  -35.980300   SPRF-PE   DEL02-PE  UOP01-DEL02-PE
37615  -35.980300   SPRF-PE   DEL02-PE  UOP01-DEL02-PE
...           ...       ...        ...             ...
170810 -48.202556       nan        nan             nan
170815 -48.202556       nan        nan             nan
170814 -48.202556       nan        nan             nan
170812 -48.202556       nan        nan             nan
170823 -48.202556       nan        nan             nan

[156373 rows x 35 columns]

In [31]:
# -------------------------------------------------------------
# CONFIGURAÇÃO DA CONEXÃO COM O POSTGRESQL
# -------------------------------------------------------------
# Formato da string de conexão: 
# postgresql://usuario:senha@endereco:porta/nome_do_banco
# Substitua pelos dados do seu ambiente:
usuario = "postgres"
senha = "postgres"
host = "localhost"
porta = "5432"
banco = "dbs_ontl"

# Cria o motor de conexão
engine = create_engine(f'postgresql://{usuario}:{senha}@{host}:{porta}/{banco}')

In [32]:
with engine.connect() as conn:
    with conn.begin():             #Cria a conexão de forma segura, garantindo que não vamos perder algo por conta de qualquer erro
        conn.execute(text("""
            DELETE FROM raw.acidentes2025
            WHERE EXTRACT(YEAR FROM data_inversa) = 2022
"""))      #Deleta os dados antigos apenas dos anos de 2025

In [33]:
df.to_sql(
    'acidentes2025',
    schema='raw',
    con=engine,
    if_exists='append',
    index=False
)

837